### ISSUE TITLE
Fix WinXP compatibility (Was: Use something instead of GetThreadId)

### ISSUE THREAD

**Issue by KevinW1998** [WohlSoft/LunaLua#2]
GetThreadId is only a API which is supported Vista and up.

> When I try to open the recent version, I get a message error about KERNEL32.dll (I guess it was "The procedure Entry Point GetThreadId could not be located in the dynamic link library KERNEL32.dll", not sure because my system is in portuguese). Is it possible to fix?

Possible fixes: http://stackoverflow.com/questions/1514969/getthreadid-on-pre-vista-systems

**Comment by Wohlstand** [comment]
I think, this may help you: https://github.com/Wohlhabend-Networks/PGE-Project/commit/5aaa9172c5052a8c4bbc814febce9f1d26a5ca7f
I had same trouble with Windows XP and editor, but I fixed than dumb mistake

**Comment by Bluenaxela** [comment]
Pretty sure the only reference to GetThreadId in LunaDLL is the following bit from StackWalker:

``` c++
#if _WIN32_WINNT <= 0x0501
      // If we need to support XP, we need to use the "old way", because "GetThreadId" is not available!
    if (hThread == GetCurrentThread())
#else
    if (GetThreadId(hThread) == GetCurrentThreadId())
#endif
```

The solution is already there, we just need to change the #if to something different (perhaps just "#if 1"), because that #if doesn't realize that we've set to toolchain to one meant to target WinXP

**Comment by Wohlstand** [comment]
It was by compilation-only solution, than means to you must built code on Windows XP to get compatible exe file. The main problem - build on any other OS same compatible exe file

**Comment by Bluenaxela** [comment]
Addressed in 311ee84b2e6dcb128648af90bd32bc7f6372d818
Untested as I don't have a Windows XP machine, but I've verified the generated .dll no longer references GetThreadId at all.

**Comment by Wohlstand** [comment]
I will try it to test now, I have Windows XP Virtual Machine

**Comment by Wohlstand** [comment]
Still not working, error on inet_pton function, it doesn't supported on Windows XP
(I fount usage of them in Lua socket part)

**Comment by KevinW1998** [comment]
Dangit.... Anyone knows a alternative to that?

**Comment by Wohlstand** [comment]
I think, I found solution in one of comments here,
http://stackoverflow.com/questions/15660203/inet-pton-identifier-not-found

I will try to apply than as custom function

**Comment by Wohlstand** [comment]
I just fixed runtime under Windows XP, but because creepy VirtualBox environment, SMBX has crashed when it tried to init title-screen. I think, we are need to test it on real environment to confirm than it will work correctly

**Comment by Bluenaxela** [comment]
I just got a Windows XP VM set up here, and I was able to reproduce the crash you describe.

On a hunch, I quickly made a build with the OpenGL renderer disabled (replace mEnabled(true) with mEnabled(false) in GLEngine.cpp) and it ran successfully.

No idea as to the underlying cause yet, but I'll probably look into it further tomorrow night (i.e. 22 hours from now probably).

**Comment by Bluenaxela** [comment]
Update: I turned on VirtualBox's 3D acceleration option, so that OpenGL would be virtualized, and that fixed it, sort of. There's a couple graphics rendered incorrectly for some reason, but it runs as opposed to crashes.

The crash is thus probably related to behaving badly when some feature is missing from the OpenGL implementation (i.e. Windows XP's default software rendering).
Not sure whether the incorrectly rendered graphics I'm seeing are an OpenGL (virtualization) issue, or a WIN32 issue during conversion of GDI images to textures.

**Comment by Wohlstand** [comment]
Yea, I knew than under VirtualBox without enabled 3D acceleration will be caused crash of SMBX. The main issue was because it doesn't wanna run under Windows XP, and it has been solved. Therefore I think, need to close it

**Comment by Bluenaxela** [comment]
It's not quite ready to close in my opinion. I'm pretty sure the incorrect graphics with the OpenGL renderer turned on are due to a difference in how Windows XP GDI loaded some bitmaps, and I ought to fix the handling of that.

**Comment by Wohlstand** [comment]
Wrong graphics render under virtualbox is normally. I tested under VirtualBox PGE Engine and had same incorrect render, BUT, while Qt Creator is running, PGE Engine renders fine. But while Qt Creator is closed - PGE Engine renders crap. Same with SMBX. I think, we are need to enable some flags which enabling by Qt Creator and everything renders correctly. You should install Windows XP on real computer and do same test. Must work fine

**Comment by Bluenaxela** [comment]
The specific way in which some graphics are rendered wrong gives me reason to think it's related to how I ignore HBITMAP.bmWidthBytes of the GDI bitmaps that are loaded. The code where I convert GDI bitmaps to OpenGL textures makes some unsafe assumptions about this, and I'm going to see if fixing those assumptions fixes the incorrect rendering. I think it will.

**Comment by Wohlstand** [comment]
Oh, you meant another thing. I catched some graphics rendered wrongly. You must align pixels to 4 bytes! I got same crap while I debugged BMP parser and got similar images. Reason is wrong byte align

**Comment by Bluenaxela** [comment]
Windows XP's version of GDI likes to do 1-byte alignment, unlike newer versions of Windows that do 4-byte alignment. I could try to detect that and set the alignment mode for OpenGL, but really... it's simpler to always use 32-bit pixels.

Fix implemented in 5bdbd792c6142b60d79b71e4312391544beba6cb

With this fix it now works perfectly in Windows XP running in VirtualBox here, provided I turn on 3D acceleration in VirtualBox.
